#macro BUTTON_WIDTH 338
#macro BUTTON_HEIGHT 64
#macro font_main global.__fontmap
#macro SCREEN_WIDTH 960
#macro SCREEN_HEIGHT 544
#macro FONT_SCALE 0.6
#macro centered 1
#macro centeredX 2
#macro centeredY 3
#macro alignRight 4
#macro alignRaw 5
#macro MENU_ITEMS_MAIN 4
#macro MENU_ITEMS_OPTIONS 6
#macro MENU_ITEMS_STATS 2
#macro MENU_ITEMS_START 5
#macro MENU_ITEMS_DIFFICULTY 2
#macro MENU_ITEMS_PAUSE 2
#macro MENU_ITEMS_GAMEOVER 2
#macro VERSION "1.0"
#macro NULL -1
#macro TOTAL_PARTICLES 3
#macro MAIN_FONT_COLOR global.__mainfontcol
